export const STRINGS = {
    RESORT_NAME: "Four Seasons Resort",
    FAVORITES: "Favorites",
    SET_THE_MOOD: "Set the Mood",
    SEARCH_PLACEHOLDER: "Search by name",
    DISTANCE_LABEL: "Distance to me",
    POPULAR_RESORTS: "Most Popular Resorts Around You",
    LETS_GO: "Let's go",
    ORDER_HISTORY: "Order History",
    DETAILS: "Details",
    PENDING: "We’ve sent your order to the resort Sit tight they’ll confirm it soon! ☀️",
    COOKING: "Cooking in Progress 🍳",
    DELIVERING: "Your Cabana Delivery’s Rolling In!",
    COMPLETED: "Everything’s here and ready to enjoy",
    PROCESSING_ORDER: "Processing Order!",
    DELIVER: "Deliver",
    IN: "in",
    MIN: "min",
    ITS_HERE: "It’s Here! 🍹",
    YOUR_ORDER_COMPLETED: "Your order completed",
    AWAITING: "Awaiting Resort Confirmation..",
    PREPARING: "Preparing your order..",
    PICKED: "Your order has been picked",
    ARRIVED: "Your Treat Has Arrived! 🍸",
    SET_MOOD: "Set the Mood",
    SET_MOOD_SUBTEXT: "Choose how you want to unwind beachfront views",
    SET_MOOD_SUBTEXT1: "cozy cabanas, or gourmet indulgence.Apply",
    SET_MOOD_SUBTEX2: "filters to create your perfect paradise.",
    YOUR_TRAY_EMPTY:"Your Tray’s Still Empty 🍸",
    CART_SUB_TEXT:"  Your cart’s as calm as a quiet beach morning. Start exploring and let Cabana Boy bring paradise to your doorstep 🌴🍹",
    LETS_FIND:"Let's find it together",
    PICK_UP_TIME:"   Pick a time slot for your repeat order and let Cabana Boy handle the rest.  Your favorite treat,ready exactly when you crave it 🍹",
    PLAN_YOUR_NEXT:"Plan Your  Indulgence!",
    
    PASSWORD_INFO: "Password must be at least 8 characters long and include a letter, number, and special character"
}
